// Code generated by fastcopier-gen. DO NOT EDIT.

//go:build !fastcopier_no_gen

package gentest

import (
	fastcopier "github.com/expego/fastcopier"
)

func init() {
	fastcopier.RegisterCopier(CopyUserEntityToUserDTO)
}

// CopyUserEntityToUserDTO copies src into dst with zero reflection overhead.
// It is auto-registered with fastcopier.RegisterCopier so that
// fastcopier.Copy(&dst, &src) routes here automatically.
// You may also call it directly for the lowest possible overhead.
func CopyUserEntityToUserDTO(dst *UserDTO, src *UserEntity) error {
	dst.ID = src.ID
	dst.Name = src.Name
	dst.Email = src.Email
	return nil
}
